### ISSUE TITLE
Development Branch Practices

### ISSUE THREAD

**Issue by ChristJohnson** [RPSkills/Origins#3]
I noticed that a commit was pushed directly to `dev` branch.

I know @RSparling and I had a brief conversation regarding branch usage. I don't believe we came to an understanding on a branching strategy. I didn't realize the possibilities until a bit earlier when I realized `feature/skill_patch` was 2 commits ahead, 1 commit behind the `dev` branch without seeing a PR. It was my understanding that we were using a trunk-based approach, which is ideal for CI/CD.

I found a page I'd like to discuss. [How to Branching Strategies](https://gitprotect.io/blog/from-novice-to-pro-understanding-git-branching-strategies/). Let me know what your thoughts are, I am for Trunk-Based development. This issue will also be a springboard for the creation of the (so far elusive) `README.md`. That will be an incoming PR to the master branch.

**Comment by PSparling32** [comment]
The commit to dev was my bad, it was supposed to be forked into a new branch but it was also late. How would you feel about a hybrid of TBD and Gitflow where we use the Development branch as our trunk and main for production?

**Comment by ChristJohnson** [comment]
I think TBD + Gitflow mitigates some of the complexity of TBD, so I'm for it. Are we rebasing before the PRs? I think that's an important thing because that's what I'd prefer. There's no guarantee the PR merges correctly without 1 of 2 conditions:

1. There are no merge conflicts (unlikely bc we're working on the same files)
2. The merge conflicts are resolved via rebase (bc that outsources conflicts to the branch.
