### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ChristJohnson** [RPSkills/Origins#5]
What licensing are we going to choose?
[Open Source Licenses](https://opensource.org/licenses/) we can choose from.
#4 to be committed with changes.

**Comment by PSparling32** [comment]
How about cc4?
https://creativecommons.org/licenses/by-nc-sa/4.0/#ref-commercial-purposes

**Comment by ChristJohnson** [comment]
For previous projects, I've always been a fan of the MIT License, but I would like attribution and the non-commercial clause. I am down. I will clear with the rest of the team.
